import { NextRequest, NextResponse } from "next/server"
import { auth, clerkClient } from "@clerk/nextjs/server"
import prisma from "@/lib/prisma"
import { GoogleGenerativeAI } from "@google/generative-ai"
import { Resend } from "resend"

// Initialize clients safely
const apiKey = process.env.GEMINI_API_KEY
const resendKey = process.env.RESEND_API_KEY

if (!apiKey) {
    console.error("[GENERATE_REPORT] Missing GEMINI_API_KEY")
}
if (!resendKey) {
    console.error("[GENERATE_REPORT] Missing RESEND_API_KEY")
}

const genAI = apiKey ? new GoogleGenerativeAI(apiKey) : null
const resend = resendKey ? new Resend(resendKey) : null

export async function POST(req: NextRequest) {
    try {
        console.log("[GENERATE_REPORT] Starting generation request...")

        if (!genAI || !resend) {
            const missing = []
            if (!genAI) missing.push("GEMINI_API_KEY")
            if (!resend) missing.push("RESEND_API_KEY")
            return NextResponse.json({ error: `Server Configuration Error: Missing ${missing.join(", ")}` }, { status: 500 })
        }

        const { userId } = await auth()
        if (!userId) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
        }

        // Verify Admin Role
        const client = await clerkClient()
        const user = await client.users.getUser(userId)
        const role = user.publicMetadata.role as string

        if (role !== "ADMIN") {
            // Fallback: Check hardcoded admin email for dev/testing if role not set
            const email = user.emailAddresses[0]?.emailAddress
            if (email !== process.env.ADMIN_EMAILS) {
                return NextResponse.json({ error: "Forbidden" }, { status: 403 })
            }
        }

        // 1. Gather Data
        const totalUsers = await prisma.user.count()
        const totalSessions = await prisma.focusSession.count()
        const recentSessions = await prisma.focusSession.findMany({
            take: 20,
            orderBy: { startTime: 'desc' },
            select: { intent: true, duration: true, mode: true, status: true }
        })
        const totalRevenueResult = await prisma.transaction.aggregate({
            where: { type: "PURCHASE" },
            _sum: { amount: true }
        })
        const totalRevenue = (totalRevenueResult._sum.amount || 0) / 100

        console.log(`[GENERATE_REPORT] Data gathered: ${totalUsers} users, ${totalSessions} sessions`)

        // 2. Generate AI Report via Gemini
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" })

        const prompt = `
            You are a ruthless business analyst. Analyze this "Locked In" app data.
            
            Data:
            - Total Users: ${totalUsers}
            - Total Sessions: ${totalSessions}
            - Total Revenue: $${totalRevenue}
            - Recent Activity: ${JSON.stringify(recentSessions)}

            Identify:
            1. Retention Risks (Are users failing sessions?)
            2. Monetization gaps.
            3. Competitive threats (Hypothetical based on low usage).
            4. Actionable items for the Admin.

            Format as HTML with <h2> and <li> tags. Keep it concise.
        `

        console.log("[GENERATE_REPORT] Calling Gemini...")
        let reportContent = "Failed to generate report."
        try {
            const result = await model.generateContent(prompt)
            reportContent = result.response.text()
            console.log("[GENERATE_REPORT] Gemini response received.")
        } catch (genError) {
            console.error("[GENERATE_REPORT] Gemini Error:", genError)
            return NextResponse.json({ error: "AI Generation Failed", details: String(genError) }, { status: 500 })
        }

        // 3. Send Email
        console.log("[GENERATE_REPORT] Sending email via Resend...")
        const adminEmail = user.emailAddresses[0].emailAddress
        console.log("[GENERATE_REPORT] Admin email:", adminEmail)

        const emailResult = await resend.emails.send({
            from: 'Locked In <onboarding@resend.dev>', // Default Resend testing domain
            to: adminEmail,
            subject: `Daily Threat Report (Gemini) - ${new Date().toLocaleDateString()}`,
            html: `
                <h1>Locked In - Threat Report</h1>
                ${reportContent}
                <hr />
                <p>Generated by Admin AI (Gemini 1.5 Flash)</p>
            `
        })
        console.log("[GENERATE_REPORT] Email result:", emailResult)

        if (emailResult.error) {
            console.error("[GENERATE_REPORT] Resend Error:", emailResult.error)
            throw new Error(emailResult.error.message)
        }

        return NextResponse.json({ success: true })

    } catch (error) {
        console.error("[GENERATE_REPORT] FATAL ERROR:", error)
        return NextResponse.json(
            { error: "Failed to generate report", details: String(error) },
            { status: 500 }
        )
    }
}
